### ISSUE TITLE
error="open ~/.ssh/id_rsa: no such file or directory" on deploy

### ISSUE THREAD

**Issue by relent0r** [darxkies/k8s-tew#1]
Hi great concept, I've been wanting to find a lightweight way of deploying.
I'm getting the id_rsa file not found error when running deploy.

ERRO[0000] deploy failed                                 error="open ~/.ssh/id_rsa: no such file or directory"

Have confirmed that $HOME/.ssh/id_rsa is present (on the node I'm running the command from) and am running the command as root.
OS is centos 7
Not sure where I'm going wrong here. I'm running the deploy command from the controller node if that makes any difference.

This is how I've configured the nodes

nodes:
  kubemaster01:
    ip: 10.1.1.197
    index: 0
    labels:
    - controller
  kubenode01:
    ip: 10.1.1.198
    index: 1
    labels:
    - worker
  kubenode02:
    ip: 10.1.1.199
    index: 2
    labels:
    - worker

**Comment by darxkies** [comment]
I fixed that in release 0.1.3. Thank you.
