### ISSUE TITLE
Coredns is starving resources in single node setup on ubuntu 18.04

### ISSUE THREAD

**Issue by AlexisDucastel** [darxkies/k8s-tew#11]
Hi,

When deploying k8s-tew 2.2.4 in standalone mode, coredns is consuming all CPU resources of the machine.

How to reproduce : 
- deploy a machine on ubuntu 18.04
- follow quickstart guide
- display htop and see "/coredns -conf /etc/coredns/Corefile" consume 330-500% CPU.

When killing coredns with -9 flag, all server is calming down, but of course, dns is not working anymore in cluster !

**Comment by AlexisDucastel** [comment]
By adding "log" section in coredns configmap in kube-system, we can see that coredns isn't actually working on out-of-the-box ubuntu 18.04 system because of /etc/resolv.conf point to 127.0.0.53, coredns is just getting connection time-out on each request, which indeed causes coredns to harvest CPU  espacially in iowait. I'm checking how to fix this.

**Comment by AlexisDucastel** [comment]
kubeadm team has already faced the problem and implemented a pre-flight check : https://github.com/kubernetes/kubernetes/pull/63691/commits

The workaround seems to be a flag ` --resolv-conf=/run/systemd/resolve/resolv.conf` to pass to kubelet on ubuntu 18.04 if the system is actually using systemd-resolved, which is the default case with ubuntu 18.04.

**Comment by AlexisDucastel** [comment]
Same case with k3s from Rancher labs : https://github.com/rancher/k3s/pull/265 !

@darxkies Do you know how to fix it in k8s-tew ?

**Comment by darxkies** [comment]
You have to run this commands:

`
k8s-tew configure --resolv-conf=/run/systemd/resolve/resolv.conf 
k8s-tew generate
`

You might also want to take a loko at this: 

https://github.com/darxkies/k8s-tew/blob/master/setup/ubuntu-single-node/Makefile

**Comment by AlexisDucastel** [comment]
Ok sorry, I missed that.

https://github.com/darxkies/k8s-tew/tree/master/setup section is very interesting ! Thanks @darxkies !

I'll update my medium post with this URL.

**Comment by darxkies** [comment]
No problem. ;)
