### ISSUE TITLE
Doesn't build on mac

### ISSUE THREAD

**Issue by figassis** [darxkies/k8s-tew#15]
It would be great if we could use this on a mac. As of now, to setup a remote cluster from a mac, I need to use vagrant and then pull the kubeconfig file, which means I can't use the k8s-tew commands.

**Comment by darxkies** [comment]
I am not sure I understand what you mean. Why do you have to use Vagrant? Unfortunately, I have no access to a mac in order to make it work. Contributions are more than welcome.

**Comment by figassis** [comment]
There are calls that I think are not supported on OSX (darwin). One error I get when building is: `pkg/container/kill.go:306:32: undefined: syscall.MNT_DETACH`

Also, I think the uuid package needs updating:
```
# github.com/darxkies/k8s-tew/config
config/config.go:48:31: multiple-value uuid.NewV4() in single-value context
```

github.com/satori/go.uuid uuid.NewV4() now returns an error as well, so we can't just do
`config.ClusterID = uuid.NewV4().String()`. Needs an intermediary variable?

I'll gladly fix the last one, will need to dive deeper to fix the first one, which I can't right now. Not sure if you know of an alternative system call for darwin?

There might be other incompatible calls, and this is just the first. To test for OSX you can do:

`GOOS=darwin GOARCH=amd64 go build`

**Comment by darxkies** [comment]
Thank you for the pull request. I will take a look at it this days.

**Comment by darxkies** [comment]
Is this issue still valid?

**Comment by figassis** [comment]
The fix allows it to build on a mac, but its a moot point as the generated binaries aren't 100% deployable on target linux machines.
