### ISSUE TITLE
No matches for kind "VolumeSnapshotClass" in version "snapshot.storage.k8s.io/v1alpha1"

### ISSUE THREAD

**Issue by figassis** [darxkies/k8s-tew#16]
I successfully installed a cluster on a previous machine, but I'm now trying with a different cluster (same machine type/specs with ubuntu 18.04), and can't get past the ceph-csi command during deploy, which returns the error:

unable to recognize "/home/user/assets/etc/k8s-tew/k8s/setup/ceph-csi.yaml\": no matches for kind "VolumeSnapshotClass" in version "snapshot.storage.k8s.io/v1alpha1"

**Comment by figassis** [comment]
It looks like the issue is that the feature gate VolumeSnapshotDataSource is not enabled in assets/etc/k8s-tew/k8s/manifests/kube-apiserver-nodename.yaml.

The file had this:
`--feature-gates=KubeletPluginsWatcher=true,CSIBlockVolume=true,BlockVolume=true`

So I had to manually add VolumeSnapshotDataSource=true for it to work.

I don't know where it failed, but it must be in the generate step.

**Comment by darxkies** [comment]
IIRC that flag is not set by default. I will add it with the next release.

**Comment by darxkies** [comment]
The change for that is already in the repository.
