### ISSUE TITLE
Kill processes on node during deploy

### ISSUE THREAD

**Issue by figassis** [darxkies/k8s-tew#17]
Whenever a deploy fails and a change requires me to run generate, I have to deploy with --force-upload. But if a file on the node is already locked by a process (eg. containerd-shim), then the deployment fails. It would be nice as a preparation to kill these processes before deploying on a node.

**Comment by darxkies** [comment]
Can you give some examples of files that are locked? Some log messages would be very helpful.

**Comment by figassis** [comment]
I don't have then anymore, but I struggled with containerd-shim, because it was always running when I tried to redeploy

**Comment by darxkies** [comment]
I did not have any issues like that. Which distribution did you use to install it to?

**Comment by figassis** [comment]
I installed k8s-tew on ubuntu 18.04 inside vagrant, and deployed on a clean remote machine, also ubuntu 18.04. I would have to ssh into the node and kill it or even delete it there sometimes

**Comment by darxkies** [comment]
Was it by any chance 18.04.3 and kernel 5.0?

**Comment by figassis** [comment]
Ubuntu 18.04.2 LTS
Kernel 4.15.0-52-generic

**Comment by darxkies** [comment]
I was able to reproduce it. In previous k8s-tew releases, all containers and processes on a node were killed before upgrading. I will enable it with the next release.

**Comment by darxkies** [comment]
When stopping k8s-tew all processes get killed.
