### ISSUE TITLE
Worked great, Thanks. 

### ISSUE THREAD

**Issue by ghost** [darxkies/k8s-tew#20]

**Comment by darxkies** [comment]
Hello to you too. Can I help you?

**Comment by mosn** [comment]
Hi There, `k8s-tew` already helped me and it really is awesome. Do you have any plan to make the CLI App more interactive, I'd love to help if that's in the roadmap.

**Comment by darxkies** [comment]
I am glad to read that. Regarding making k8s-tew more interactive. As a matter of fact, I did think about that often in the last 12 months. Either some kind of console based wizard or a web-based UI (using Vuetify). Contributions and ideas are more than welcome. :)

**Comment by mosn** [comment]
I proposed [something](http://bit.ly/2lVvMTi) to che team for `[chectl](https://github.com/che-incubator/chectl)` which had the same level of complexity, unfortunately as it turns out it's not the right for che but maybe we can use it for k8s-tew. You can find the proposal here 
http://bit.ly/2lVvMTi
If that's close to what you have in mind, maybe we can take it from there.

**Comment by darxkies** [comment]
It looks very interesting. A while ago, I did some digging into libraries to achieve that kind of functionality.

**Comment by mosn** [comment]
Something like this is being used by some other known repos.
https://asciinema.org/a/jRxJlU2CNMGB3r8mcOBrANsvS

but I can also see that non of them share the complexity and also they need for better progress monitor. 

If theres an issue we can collect requirments, I can dedicate a few hours this weekend to work on it.

**Comment by darxkies** [comment]
Feel free to add the issue. To be clear. You want to implement that kind of interactivity only for the configuration part right? And only Go will be used?

**Comment by mosn** [comment]
that is the idea, unless I am missing a something bigger, by adding one more two libraries we can add the interactive functionality and also make it easier to change the prompt in the future & bring support for multi language. This all is encapsulated in it's own files and will not affect the program itself.

**Comment by darxkies** [comment]
k8s-tew is one staticly linked binary without any dependencies for easy deployment. As long as it stays that way everything is going to be just fine. :)
