### ISSUE TITLE
Uninstall k8s-tew completly

### ISSUE THREAD

**Issue by martincolladoio** [darxkies/k8s-tew#21]
Recently I've tried the k8s-tew project following the steps described. But now I'd like to completly remove from my system everything. How to proceed? What steps are involved to remove everything?

**Comment by darxkies** [comment]
How did you install it? On the host system? Or on a remote server?

**Comment by martincolladoio** [comment]
I installed it from this guide: 
https://itnext.io/kubernetes-on-bare-metal-batteries-included-with-k8s-tew-b7df7d661443

On remote server (ubuntu server 18.04)
Cheers

**Comment by darxkies** [comment]
You need to execute the following instructions as root:

systemctl stop k8s-tew
systemctl disable k8s-tew
reboot
rm -Rf /etc/systemd/system/k8s-tew.service /etc/systemd/system/multi-user.target.wants/k8s-tew.service /etc/k8s-tew /etc/bash_completion.d/k8s-tew.bash-completion /etc/profile.d/k8s-tew.sh /var/k8s-tew /var/log/k8s-tew /var/lib/k8s-tew /opt/k8s-tew /run/k8s-tew  /run/containerd /opt/containerd /var/log/pods /var/lib/kubelet

**Comment by martincolladoio** [comment]
Cheers! I'll try it later

**Comment by eddieparker** [comment]
I followed these instructions but now I have a rogue KUBECONFIG=/etc/k8s-tew/k8s/kubeconfig/admin.kubeconfig everytime I log in.

Do you know where this is set?

**Comment by darxkies** [comment]
That is set in /etc/profile.d/k8s-tew.sh in the last line. But that file is removed with the rm shell command above. Try rebooting after the rm command. Afterwards the settings should be gone for good.
