### ISSUE TITLE
ERRO[0456] Cluster setup failed

### ISSUE THREAD

**Issue by memphizz** [darxkies/k8s-tew#23]
I am trying to do a single node install on ubuntu 18.04 (local bare-metal). I get this error when I try to execute run. any idea what the issue is?
here is the output for node-list (I used defaults for config):
k8s-tew node-list
INFO[0000] Node                                          index=0 ip=10.200.26.80 labels="[bootstrapper controller worker]" name=gpx10

ERRO[0456] Command failed                                command="/home/user/k8-tew/assets/opt/k8s-tew/bin/k8s/kubectl --request-timeout 30s --kubeconfig /home/user/k8-tew/assets/etc/k8s-tew/k8s/kubeconfig/admin.kubeconfig apply -f /home/user/k8-tew/assets/etc/k8s-tew/k8s/setup/ceph-csi.yaml" error="Command '/home/user/k8-tew/assets/opt/k8s-tew/bin/k8s/kubectl --request-timeout 30s --kubeconfig /home/user/k8-tew/assets/etc/k8s-tew/k8s/kubeconfig/admin.kubeconfig apply -f /home/user/k8-tew/assets/etc/k8s-tew/k8s/setup/ceph-csi.yaml' failed with error 'exit status 1' (Output: storageclass.storage.k8s.io/csi-rbd unchanged\nstorageclass.storage.k8s.io/csi-cephfs unchanged\nserviceaccount/cephfs-csi-attacher unchanged\nclusterrole.rbac.authorization.k8s.io/cephfs-external-attacher-runner unchanged\nclusterrolebinding.rbac.authorization.k8s.io/cephfs-csi-attacher-role unchanged\nservice/csi-cephfsplugin-attacher unchanged\nstatefulset.apps/csi-cephfsplugin-attacher unchanged\nservice/csi-cephfsplugin-provisioner unchanged\nstatefulset.apps/csi-cephfsplugin-provisioner unchanged\ndaemonset.apps/csi-cephfsplugin unchanged\nserviceaccount/cephfs-csi-nodeplugin unchanged\nclusterrole.rbac.authorization.k8s.io/cephfs-csi-nodeplugin unchanged\nclusterrolebinding.rbac.authorization.k8s.io/cephfs-csi-nodeplugin unchanged\nserviceaccount/cephfs-csi-provisioner unchanged\nclusterrole.rbac.authorization.k8s.io/cephfs-external-provisioner-runner unchanged\nclusterrolebinding.rbac.authorization.k8s.io/cephfs-csi-provisioner-role unchanged\nrole.rbac.authorization.k8s.io/cephfs-external-provisioner-cfg unchanged\nrolebinding.rbac.authorization.k8s.io/cephfs-csi-provisioner-role-cfg unchanged\nserviceaccount/rbd-csi-attacher unchanged\nclusterrole.rbac.authorization.k8s.io/rbd-external-attacher-runner unchanged\nclusterrolebinding.rbac.authorization.k8s.io/rbd-csi-attacher-role unchanged\nserviceaccount/rbd-csi-nodeplugin unchanged\nclusterrole.rbac.authorization.k8s.io/rbd-csi-nodeplugin unchanged\nclusterrolebinding.rbac.authorization.k8s.io/rbd-csi-nodeplugin unchanged\nserviceaccount/rbd-csi-provisioner unchanged\nclusterrole.rbac.authorization.k8s.io/rbd-external-provisioner-runner unchanged\nclusterrolebinding.rbac.authorization.k8s.io/rbd-csi-provisioner-role unchanged\nrole.rbac.authorization.k8s.io/rbd-external-provisioner-cfg unchanged\nrolebinding.rbac.authorization.k8s.io/rbd-csi-provisioner-role-cfg unchanged\nservice/csi-rbdplugin-attacher unchanged\nstatefulset.apps/csi-rbdplugin-attacher unchanged\nservice/csi-rbdplugin-provisioner unchanged\nstatefulset.apps/csi-rbdplugin-provisioner unchanged\ndaemonset.apps/csi-rbdplugin unchanged\nerror: unable to recognize \"/home/user/k8-tew/assets/etc/k8s-tew/k8s/setup/ceph-csi.yaml\": no matches for kind \"VolumeSnapshotClass\" in version \"snapshot.storage.k8s.io/v1alpha1\"\n)" name=ceph-csi
ERRO[0456] Cluster setup failed                          error="Command '/home/user/k8-tew/assets/opt/k8s-tew/bin/k8s/kubectl --request-timeout 30s --kubeconfig /home/user/k8-tew/assets/etc/k8s-tew/k8s/kubeconfig/admin.kubeconfig apply -f /home/user/k8-tew/assets/etc/k8s-tew/k8s/setup/ceph-csi.yaml' failed with error 'exit status 1' (Output: storageclass.storage.k8s.io/csi-rbd unchanged\nstorageclass.storage.k8s.io/csi-cephfs unchanged\nserviceaccount/cephfs-csi-attacher unchanged\nclusterrole.rbac.authorization.k8s.io/cephfs-external-attacher-runner unchanged\nclusterrolebinding.rbac.authorization.k8s.io/cephfs-csi-attacher-role unchanged\nservice/csi-cephfsplugin-attacher unchanged\nstatefulset.apps/csi-cephfsplugin-attacher unchanged\nservice/csi-cephfsplugin-provisioner unchanged\nstatefulset.apps/csi-cephfsplugin-provisioner unchanged\ndaemonset.apps/csi-cephfsplugin unchanged\nserviceaccount/cephfs-csi-nodeplugin unchanged\nclusterrole.rbac.authorization.k8s.io/cephfs-csi-nodeplugin unchanged\nclusterrolebinding.rbac.authorization.k8s.io/cephfs-csi-nodeplugin unchanged\nserviceaccount/cephfs-csi-provisioner unchanged\nclusterrole.rbac.authorization.k8s.io/cephfs-external-provisioner-runner unchanged\nclusterrolebinding.rbac.authorization.k8s.io/cephfs-csi-provisioner-role unchanged\nrole.rbac.authorization.k8s.io/cephfs-external-provisioner-cfg unchanged\nrolebinding.rbac.authorization.k8s.io/cephfs-csi-provisioner-role-cfg unchanged\nserviceaccount/rbd-csi-attacher unchanged\nclusterrole.rbac.authorization.k8s.io/rbd-external-attacher-runner unchanged\nclusterrolebinding.rbac.authorization.k8s.io/rbd-csi-attacher-role unchanged\nserviceaccount/rbd-csi-nodeplugin unchanged\nclusterrole.rbac.authorization.k8s.io/rbd-csi-nodeplugin unchanged\nclusterrolebinding.rbac.authorization.k8s.io/rbd-csi-nodeplugin unchanged\nserviceaccount/rbd-csi-provisioner unchanged\nclusterrole.rbac.authorization.k8s.io/rbd-external-provisioner-runner unchanged\nclusterrolebinding.rbac.authorization.k8s.io/rbd-csi-provisioner-role unchanged\nrole.rbac.authorization.k8s.io/rbd-external-provisioner-cfg unchanged\nrolebinding.rbac.authorization.k8s.io/rbd-csi-provisioner-role-cfg unchanged\nservice/csi-rbdplugin-attacher unchanged\nstatefulset.apps/csi-rbdplugin-attacher unchanged\nservice/csi-rbdplugin-provisioner unchanged\nstatefulset.apps/csi-rbdplugin-provisioner unchanged\ndaemonset.apps/csi-rbdplugin unchanged\nerror: unable to recognize \"/home/user/k8-tew/assets/etc/k8s-tew/k8s/setup/ceph-csi.yaml\": no matches for kind \"VolumeSnapshotClass\" in version \"snapshot.storage.k8s.io/v1alpha1\"\n)"

**Comment by darxkies** [comment]
Can you post the version you used and the steps?

**Comment by memphizz** [comment]
Thanks for the response. Not sure what happened but it's working now.
