### ISSUE TITLE
How can we use istio sidecar and its loadbalancers

### ISSUE THREAD

**Issue by entrymon** [darxkies/k8s-tew#34]
Where does istio fit in here, is there a way to configure it and use istio as sidecar and loadbalncer.

Also anyway no to install Wordpress and instead any other image?

**Comment by darxkies** [comment]
I did install Istio with k8s-tew for a project. But the overhead was so big in terms of resources consumed that I gave it up. I was thinking of integrating it into k8s-tew. I used the Istio Howto to install it. 

I do not understand the second question. Do you want to install Wordpress but you want to use another image? If yes, you can use the k8s-tew configuration parameter to specify which image to be used.

**Comment by entrymon** [comment]
Regarding 
-1 Thanks, some components of istio and your setup overlap so was wondering how we can have both
-2 The question was instead of WordPress can we use any other image to test the setup? Or skip WordPress entirely.

**Comment by darxkies** [comment]
1) Even if they are overlapping it should work just fine. If not let me know.
2) To use another image for WordPress you need the the command:

k8s-tew configure --version-wordpress docker.io/library/wordpress:5.4-apache

You need to replace the last part with the image you want.

To skip WordPress altogether:

k8s-tew deploy --skip-showcase-setup

**Comment by darxkies** [comment]
If you have already installed WordPress you can remove the namespace showcase. That will wipe WordPress out.

**Comment by entrymon** [comment]
I have a bare metal server with 16 cores and 64gb ram, is there any way using k8s-tew’s that I can create more than one node cluster on this hardware? If I use it as it is, it creates only 1 node with minikube I have the option to create --nodes=3.

**Comment by darxkies** [comment]
You need something like this. It creates a cluster of 5 nodes (3 controllers, 2 workers/storage). It also creates the Vagrant VMs for you. 

https://github.com/darxkies/k8s-tew/blob/master/setup/ubuntu-multi-node/Makefile

But you can also use kvm or multipass or qemu.
