### ISSUE TITLE
k8s-tew run failed

### ISSUE THREAD

**Issue by ameyaagashe** [darxkies/k8s-tew#5]
Hi mate,

I was running k8s-tew run and it failed with the below information.

`[ERRO[0326] Restarting server                             command="/home/jim/assets/opt/k8s-tew/bin/k8s/kube-apiserver --bind-address=0.0.0.0 --kubelet-client-certificate=/home/jim/assets/etc/k8s-tew/ssl/kubernetes.pem --proxy-client-key-file=/home/jim/assets/etc/k8s-tew/ssl/aggregator-key.pem --requestheader-allowed-names=aggregator,admin,system:kube-controller-manager,system:kube-controller-manager,system:kube-scheduler,system:node:centos74.master --tls-private-key-file=/home/jim/assets/etc/k8s-tew/ssl/kubernetes-key.pem --apiserver-count=2 --etcd-keyfile=/home/jim/assets/etc/k8s-tew/ssl/kubernetes-key.pem --kubelet-certificate-authority=/home/jim/assets/etc/k8s-tew/ssl/ca.pem --advertise-address=192.168.4.222 --allow-privileged=true --audit-log-path=/home/jim/assets/var/log/k8s-tew/audit.log --enable-admission-plugins=Initializers,NamespaceLifecycle,NodeRestriction,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota --etcd-cafile=/home/jim/assets/etc/k8s-tew/ssl/ca.pem --feature-gates=KubeletPluginsWatcher=true,CSIBlockVolume=true,BlockVolume=true --requestheader-group-headers=X-Remote-Group --audit-log-maxage=30 --audit-log-maxbackup=3 --audit-log-maxsize=100 --enable-swagger-ui=true --requestheader-client-ca-file=/home/jim/assets/etc/k8s-tew/ssl/ca.pem --service-node-port-range=30000-32767 --tls-cert-file=/home/jim/ERRO[0329] Command failed                                command="systemctl disable firewalld && systemctl stop firewalld && setenforce 0 && sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux" error="Command 'systemctl disable firewalld && systemctl stop firewalld && setenforce 0 && sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux' failed with error 'exit status 1' (Output: setenforce: SELinux is disabled\n)" name=setup-centos        [/] PrFATA[0329] Cluster setup failed                          error="Command 'systemctl disable firewalld && systemctl stop firewalld && setenforce 0 && sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux' failed with error 'exit status 1' (Output: setenforce: SELinux is disabled](url)`

Not sure what is the reason but I did restart the server.

OS=CentOS 7.5 installed on Windows 10 Enterprise, Virtualisation Software Virtualbox

Kind Regards,
Ameya Agashe

**Comment by darxkies** [comment]
Did you get that error only after rebooting? Did it work before the reboot? Did you install centos 7.5 from iso in VirtualBox?

**Comment by ameyaagashe** [comment]
Yes, it happened before reboot as well. Yes, I did install CentOS 7.5 from ISO in Virtualbox.

**Comment by darxkies** [comment]
I fixed that issue in the new release [2.1.0-beta.5](https://github.com/darxkies/k8s-tew/releases/tag/2.1.0-beta.5)

After downloading k8s-tew, remove /home/jim/assets/etc and recreate the cluster (k8s-tew initialize,.....). Let me know if that works for you.

**Comment by ameyaagashe** [comment]
Ok, let me re-run with 2.1.0-beta.5 and provide you feedback.

**Comment by darxkies** [comment]
Did it work for you?

**Comment by ameyaagashe** [comment]
I did try but it was not producing any output. I need to try again after a fresh clone from the previous know restore point.

**Comment by darxkies** [comment]
Perhaps this link will help you: https://darxkies.github.io/k8s-tew/_build/html/quickstart.html

**Comment by ameyaagashe** [comment]
Thanks, mate, certainly, I will, just need few days time to build one environment and then I would take a look. SIncere apologies for the delay in response.

**Comment by darxkies** [comment]
Don't worry. If you need help let me know. ;)

**Comment by ameyaagashe** [comment]
Hey, I am back. Have you merged the change to master? Want to create from start. Please let me know. Thanks
Ameya

**Comment by darxkies** [comment]
You should use the latest version [2.1.0](https://github.com/darxkies/k8s-tew/releases/download/2.1.0/k8s-tew). Please use the [quick start guide](https://darxkies.github.io/k8s-tew/_build/html/quickstart.html) to get started.
