### ISSUE TITLE
Where can I find the kubeconfig or token to log into the dashboard?

### ISSUE THREAD

**Issue by leonj1** [darxkies/k8s-tew#6]
I've started a multi-node cluster (1 controller and 2 workers) successfully.
I can list PODs, nodes, etc.
But for the life of me I cannot figure out where to get the credentials to log into the dashboard.
Usually, I get the kubeconfig from the controller, or look for a ~/.kube/config file but none of those have worked. The last Kube cluster version I've worked in was 1.9 and maybe creds locations have changed since then.

```
# Commands I've used to spin up a cluster
cd setup/ubuntu-multi-node
make run
eval $(k8s-tew environment)
make dashboard
```
Fork where I'm tracking my changes: https://github.com/leonj1/k8s-tew/tree/multi_node

**Comment by darxkies** [comment]
k8s-tew generates everything in the directory assets (or other defined <base-directory>). The kubeconfig you are looking for is  assets/etc/k8s-tew/k8s/kubeconfig/admin.kubeconfig. The command `eval $(k8s-tew environment)` sets a couple of environment variables and one of them is KUBECONFIG which points to admin.kubeconfig. You can simply run `k8s-tew environment` to see all environment variables which are set.

The dashboard token on the other side can be displayed with either `make dashboard` or `k8s-tew dashboard` and it is retrieved from the cluster and not stored anywhere.

**Comment by leonj1** [comment]
Ah! User error. Previously I didnt copy the full token that gets displayed when dashboard is invoked. All's well now. Thanks! This is awesome!

**Comment by darxkies** [comment]
Have fun. ;)
